In [18]:
from numpy import *
import operator

def createDataSet():
    group = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','A','B','B']
    return group, labels

def classify0(inX,dataset,labels,k):
    datasetsize = dataset.shape[0]
    diffMat = tile(inX,(datasetsize,1))- dataset
    sqDiffMat = diffMat**2
    print (sqDiffMat)
    sqDistances = sqDiffMat.sum(axis=1)
    print (sqDistances)
    distances = sqDistances**0.5
    sortedDisIndicies = distances.argsort()
    classCount = {}
    for i in range(k):
        voteIlabel = labels[sortedDisIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0)+1
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
    return sortedClassCount[0][0]


In [19]:
group,labels = createDataSet()
classify0([0,0],group,labels,3)

[[1.   1.21]
 [1.   1.  ]
 [0.   0.  ]
 [0.   0.01]]
[2.21 2.   0.   0.01]


'B'

In [3]:
tile([0,0],(4,1))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])